import { IconDefinition, library } from '@fortawesome/fontawesome-svg-core'
import { faCircle } from '@fortawesome/free-regular-svg-icons';
import {
    faCheck,
    faCircleCheck,
    faFileInvoice,
    faMinus,
    faPlus,
    faTrash,
    faTriangleExclamation,
    faEdit,
    faGrip,
    faArrowRotateRight,
    faArrowsRotate,
    faEye,
    faEyeSlash,
    faArrowLeft,
    faSquarePlus,
    faUpRightFromSquare,
    faHeading,
    faBorderTopLeft,
    faGripLines,
    faGear,
    faBrush,
    faMaximize,
    faMinimize,
    faSun,
    faMoon,
    faCrop,
    faSpinner,
    faFilePdf,
    faLink,
    faFileZipper,
    faFileWord,
    faFileExcel,
    faFilePowerpoint,
    faArrowsDownToLine,
    faCubes,
    faPager,
    faPalette,
    faPhotoFilm,
    faGears,
    faToolbox,
    faClone,
    faListCheck,
} from '@fortawesome/free-solid-svg-icons'
import { faCss3, faJs } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(
    faTriangleExclamation,
    faPlus,
    faMinus,
    faCheck,
    faTrash,
    faFileInvoice,
    faCircle,
    faCircleCheck,
    faEdit,
    faGrip,
    faGripLines,
    faArrowRotateRight,
    faArrowsRotate,
    faEye,
    faEyeSlash,
    faArrowLeft,
    faSquarePlus,
    faUpRightFromSquare,
    faHeading,
    faBorderTopLeft,
    faGear,
    faBrush,
    faMaximize,
    faMinimize,
    faSun,
    faMoon,
    faCrop,
    faSpinner,
    faFilePdf,
    faLink,
    faFileZipper,
    faFileWord,
    faFileExcel,
    faFilePowerpoint,
    faArrowsDownToLine,
    faCubes,
    faPager,
    faPalette,
    faJs as IconDefinition,
    faCss3 as IconDefinition,
    faPhotoFilm,
    faGears,
    faToolbox,
    faClone,
    faListCheck 
);

export default FontAwesomeIcon;

